code --install-extension RobinMalfait.prettier-eslint-vscode
code --install-extension alefragnani.project-manager
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension EditorConfig.EditorConfig
code --install-extension Equinusocio.vsc-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension ms-vscode.sublime-keybindings
code --install-extension ms-vscode.Theme-MaterialKit
code --install-extension Orta.vscode-jest
code --install-extension PeterJausovec.vscode-docker
code --install-extension robinbentley.sass-indented
code --install-extension ryuta46.multi-command
code --install-extension Shan.code-settings-sync
code --install-extension shinnn.stylelint
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wix.vscode-import-cost
code --install-extension xabikos.ReactSnippets
